###Get the Service document.
http://localhost:4004/odata/v4/EmployeeService

###Get the Service metadata document.
http://localhost:4004/odata/v4/EmployeeService/$metadata

###Get all the Employees data.
http://localhost:4004/odata/v4/EmployeeService/EmployeeSet

###Get all the Employees whose name starts with ‘S’.
http://localhost:4004/odata/v4/EmployeeService/EmployeeSet?$filter=contains(nameFirst,'S')

###CREATE an employee with salary <50000 & currency code USD.
POST http://localhost:4004/odata/v4/EmployeeService/EmployeeSet
Content-Type: application/json

{
  "nameFirst": "DharaniI",
  "nameMiddle": null,
  "nameLast": "penta",
  "nameInitials": null,
  "sex": "F",
  "language": "E",
  "phoneNumber": "+917815855107",
  "email": "dharani.p@gmail.com",
  "loginName": "SPRINGS",
  "Currency_code": "USD",
  "salaryAmount": 49999,
  "accountNumber": "111222333",
  "bankId": "511000655",
  "bankName": "My Bank of Antioch"
}


###CREATE an employee with salary >50000 & currency code USD.
POST http://localhost:4004/odata/v4/EmployeeService/EmployeeSet
Content-Type: application/json

{
  "nameFirst": "Sailaja",
  "nameMiddle": null,
  "nameLast": "penta",
  "nameInitials": null,
  "sex": "F",
  "language": "E",
  "phoneNumber": "+917995578078",
  "email": "dharani.p@gmail.com",
  "loginName": "SPRINGS",
  "Currency_code": "USD",
  "salaryAmount": 59999,
  "accountNumber": "111222333",
  "bankId": "511000655",
  "bankName": "My Bank of Antioch"
}

###CREATE an employee with salary <50000 & currency code EUR.
POST http://localhost:4004/odata/v4/EmployeeService/EmployeeSet
Content-Type: application/json

{
  "nameFirst": "Sailaj",
  "nameMiddle": null,
  "nameLast": "penta",
  "nameInitials": null,
  "sex": "F",
  "language": "E",
  "phoneNumber": "+917995578078",
  "email": "dharani.p@gmail.com",
  "loginName": "SPRINGS",
  "Currency_code": "EUR",
  "salaryAmount": 49999,
  "accountNumber": "111222333",
  "bankId": "511000655",
  "bankName": "My Bank of Antioch"
}

###Get the data 
http://localhost:4004/odata/v4/EmployeeService/EmployeeSet/adccee8a-56ae-4212-a7ad-3bfeb800911c

###UPDATE an employee by keeping the nameFirst and loginName intact.

PATCH http://localhost:4004/odata/v4/EmployeeService/EmployeeSet/adccee8a-56ae-4212-a7ad-3bfeb800911c
Content-Type: application/json

{
    
  "salaryAmount": 40000,
  "Currency_code": "USD"
}

###UPDATE an employee by changing the loginName.
PATCH http://localhost:4004/odata/v4/EmployeeService/EmployeeSet/adccee8a-56ae-4212-a7ad-3bfeb800911c
Content-Type: application/json

{
   "loginName": "newloginname"
 
}

###DELETE any employee.
DELETE http://localhost:4004/odata/v4/EmployeeService/EmployeeSet/adccee8a-56ae-4212-a7ad-3bfeb800911c

###DELETE an employee whose nameFirst starts with ‘S’.
DELETE http://localhost:4004/odata/v4/EmployeeServices/employees/02BD2137-0890-1EEA-A6C2-BB55C19787FB



